DISCLAIMER = (
    "Prototype only: this tool does not provide a diagnosis and should not replace a licensed clinician."
)

FALLBACK_QUESTIONS = [
    "How long have the symptoms been present?",
    "What is the severity: mild, moderate, or severe?",
    "Are there associated symptoms such as fever, vomiting, or breathing difficulty?",
    "Does the person have any major medical history or current medicines?",
]

SYMPTOM_PATTERNS = [
    {
        "title": "Respiratory infection pattern",
        "priority": 9,
        "risk_level": "Medium",
        "urgency": "Home care with monitoring",
        "summary": "Fever with cough commonly appears in viral respiratory infections and needs hydration, rest, and watchful monitoring.",
        "possible_conditions": ["Viral fever", "Influenza", "COVID-like illness", "Upper respiratory infection"],
        "care_advice": ["Drink fluids regularly.", "Rest and monitor temperature.", "Seek in-person care if fever persists or worsens."],
        "red_flags": ["Breathing difficulty", "Persistent high fever", "Confusion", "Low oxygen if monitored"],
        "follow_up_questions": ["How many days has the fever been present?", "Is the cough dry or with mucus?", "Is there any breathing difficulty?"],
        "keywords_all": ["fever", "cough"],
        "keywords_any": [],
        "matched_keywords": ["fever", "cough"],
    },
    {
        "title": "Gastrointestinal upset pattern",
        "priority": 8,
        "risk_level": "Medium",
        "urgency": "Monitor hydration",
        "summary": "Vomiting with diarrhea may suggest food poisoning or gastroenteritis, with dehydration being the main short-term risk.",
        "possible_conditions": ["Food poisoning", "Gastroenteritis", "Stomach infection"],
        "care_advice": ["Use oral rehydration fluids if available.", "Take small sips frequently.", "Avoid oily or spicy foods until better."],
        "red_flags": ["Blood in stool", "Unable to keep fluids down", "Severe weakness", "Reduced urination"],
        "follow_up_questions": ["How often is vomiting or diarrhea happening?", "Any fever or abdominal pain?", "Was any outside or stale food eaten recently?"],
        "keywords_all": ["vomiting", "diarrhea"],
        "keywords_any": [],
        "matched_keywords": ["vomiting", "diarrhea"],
    },
    {
        "title": "Headache or migraine pattern",
        "priority": 6,
        "risk_level": "Low to Medium",
        "urgency": "Observation and routine consultation if recurring",
        "summary": "Headache can be linked with stress, dehydration, eye strain, or migraine features.",
        "possible_conditions": ["Migraine", "Tension headache", "Dehydration", "Sinus-related headache"],
        "care_advice": ["Rest in a quiet area.", "Drink water.", "Reduce screen exposure for a while."],
        "red_flags": ["Sudden worst-ever headache", "Weakness or slurred speech", "Repeated vomiting", "High fever with neck stiffness"],
        "follow_up_questions": ["Is there sensitivity to light or sound?", "Any fever or vomiting?", "Is this a new or recurrent headache?"],
        "keywords_all": ["headache"],
        "keywords_any": [],
        "matched_keywords": ["headache"],
    },
    {
        "title": "Chest pain emergency pattern",
        "priority": 10,
        "risk_level": "High",
        "urgency": "Immediate medical attention",
        "summary": "Chest pain with pressure, sweating, or breathing difficulty can indicate a serious heart or lung issue.",
        "possible_conditions": ["Heart attack", "Angina", "Pulmonary embolism", "Severe acid reflux"],
        "care_advice": ["Seek emergency care immediately.", "Avoid heavy activity.", "Keep the patient calm while waiting for help."],
        "red_flags": ["Pain spreading to arm or jaw", "Sweating", "Shortness of breath", "Loss of consciousness"],
        "follow_up_questions": ["How long has the chest pain lasted?", "Does it spread anywhere?", "Any history of heart disease?"],
        "keywords_all": ["chest pain"],
        "keywords_any": [["shortness of breath", "breathing difficulty"]],
        "matched_keywords": ["chest pain", "shortness of breath"],
    },
    {
        "title": "Diabetes warning pattern",
        "priority": 7,
        "risk_level": "Medium to High",
        "urgency": "Medical review advised",
        "summary": "Frequent urination and excessive thirst may suggest high blood sugar or diabetes.",
        "possible_conditions": ["Diabetes", "High blood sugar", "Dehydration"],
        "care_advice": ["Drink water regularly.", "Reduce sugary drinks.", "Arrange blood sugar testing."],
        "red_flags": ["Confusion", "Vomiting", "Rapid breathing", "Severe fatigue"],
        "follow_up_questions": ["Any recent weight loss?", "How often is urination happening?", "Any family history of diabetes?"],
        "keywords_all": [],
        "keywords_any": [["frequent urination", "urinating often"], ["excessive thirst", "very thirsty"]],
        "matched_keywords": ["frequent urination", "excessive thirst"],
    },
    {
        "title": "Allergic reaction pattern",
        "priority": 8,
        "risk_level": "Medium to High",
        "urgency": "Urgent evaluation if worsening",
        "summary": "Rash, itching, or swelling may occur from allergies, medications, or environmental triggers.",
        "possible_conditions": ["Allergic reaction", "Food allergy", "Medication allergy", "Skin irritation"],
        "care_advice": ["Avoid known triggers.", "Keep skin clean and cool.", "Seek help if symptoms spread quickly."],
        "red_flags": ["Facial swelling", "Breathing difficulty", "Rapidly spreading rash", "Dizziness"],
        "follow_up_questions": ["Any new foods or medicines?", "Is there swelling?", "Any trouble breathing?"],
        "keywords_all": [],
        "keywords_any": [["rash", "skin rash"], ["itching", "itchy"]],
        "matched_keywords": ["rash", "itching"],
    },
    {
        "title": "Urinary tract infection pattern",
        "priority": 8,
        "risk_level": "High",
        "urgency": "Same-day medical review",
        "summary": "Painful urination with back pain or fever can suggest a urinary infection or kidney involvement.",
        "possible_conditions": ["Urinary tract infection", "Kidney infection", "Kidney stone"],
        "care_advice": ["Drink water regularly.", "Seek evaluation soon.", "Do not ignore fever or worsening pain."],
        "red_flags": ["Blood in urine", "High fever", "Vomiting", "Severe flank pain"],
        "follow_up_questions": ["Is there fever?", "Any blood in urine?", "How severe is the pain?"],
        "keywords_all": ["back pain"],
        "keywords_any": [["painful urination", "burning urination"]],
        "matched_keywords": ["back pain", "painful urination"],
    },
    {
        "title": "Asthma or breathing issue pattern",
        "priority": 9,
        "risk_level": "High",
        "urgency": "Urgent medical review",
        "summary": "Wheezing and breathing difficulty may suggest asthma, allergy, or airway infection.",
        "possible_conditions": ["Asthma attack", "Bronchitis", "Allergic airway reaction"],
        "care_advice": ["Avoid smoke or dust.", "Use prescribed inhaler if available.", "Seek care if symptoms worsen."],
        "red_flags": ["Blue lips", "Unable to speak properly", "Chest tightness", "Low oxygen"],
        "follow_up_questions": ["Any history of asthma?", "Is wheezing present?", "Any fever or cough?"],
        "keywords_all": [],
        "keywords_any": [["wheezing", "whistling sound"], ["breathing difficulty", "shortness of breath"]],
        "matched_keywords": ["wheezing", "breathing difficulty"],
    },
    {
        "title": "Dehydration pattern",
        "priority": 7,
        "risk_level": "Medium",
        "urgency": "Hydration and monitoring",
        "summary": "Dry mouth, weakness, and dizziness can suggest dehydration, especially after illness or heat exposure.",
        "possible_conditions": ["Dehydration", "Heat exhaustion", "Fluid loss"],
        "care_advice": ["Drink oral fluids slowly.", "Rest in a cool place.", "Monitor urine output."],
        "red_flags": ["Fainting", "Confusion", "Very low urination", "Rapid heartbeat"],
        "follow_up_questions": ["Any vomiting or diarrhea?", "How much fluid intake today?", "Any heat exposure?"],
        "keywords_all": [],
        "keywords_any": [["dizziness", "lightheaded"], ["dry mouth", "dehydrated"]],
        "matched_keywords": ["dizziness", "dry mouth"],
    },
    {
        "title": "Appendicitis concern pattern",
        "priority": 9,
        "risk_level": "High",
        "urgency": "Emergency evaluation",
        "summary": "Right lower abdominal pain with fever or vomiting may suggest appendicitis.",
        "possible_conditions": ["Appendicitis", "Abdominal infection"],
        "care_advice": ["Avoid heavy meals.", "Seek urgent medical assessment.", "Do not delay if pain worsens."],
        "red_flags": ["Severe abdominal pain", "Persistent vomiting", "Fever", "Difficulty walking"],
        "follow_up_questions": ["Where exactly is the pain located?", "Any vomiting or fever?", "Does movement worsen the pain?"],
        "keywords_all": ["abdominal pain"],
        "keywords_any": [["right side pain", "lower right abdomen"]],
        "matched_keywords": ["abdominal pain", "right side pain"],
    },
    {
        "title": "Stroke warning pattern",
        "priority": 10,
        "risk_level": "Critical",
        "urgency": "Immediate emergency care",
        "summary": "Sudden weakness, speech difficulty, or facial drooping may indicate stroke symptoms.",
        "possible_conditions": ["Stroke", "Transient ischemic attack"],
        "care_advice": ["Call emergency services immediately.", "Keep the patient safe and seated.", "Note symptom start time."],
        "red_flags": ["Slurred speech", "One-sided weakness", "Confusion", "Loss of balance"],
        "follow_up_questions": ["When did symptoms start?", "Is one side weaker?", "Any trouble speaking?"],
        "keywords_all": [],
        "keywords_any": [["slurred speech", "speech difficulty"], ["weakness", "one sided weakness"]],
        "matched_keywords": ["slurred speech", "weakness"],
    },
    {
        "title": "Anemia or fatigue pattern",
        "priority": 5,
        "risk_level": "Low to Medium",
        "urgency": "Routine consultation",
        "summary": "Fatigue and pale appearance may relate to anemia, poor sleep, stress, or nutritional deficiency.",
        "possible_conditions": ["Anemia", "Nutritional deficiency", "Stress-related fatigue"],
        "care_advice": ["Maintain balanced nutrition.", "Ensure adequate sleep.", "Arrange testing if persistent."],
        "red_flags": ["Chest pain", "Shortness of breath", "Fainting", "Rapid heartbeat"],
        "follow_up_questions": ["How long has fatigue been present?", "Any dizziness?", "Any known anemia history?"],
        "keywords_all": ["fatigue"],
        "keywords_any": [["pale", "paleness"]],
        "matched_keywords": ["fatigue", "pale"],
    },
    {
        "title": "Joint pain or arthritis pattern",
        "priority": 5,
        "risk_level": "Low to Medium",
        "urgency": "Routine medical review",
        "summary": "Joint pain and stiffness may be linked to arthritis, strain, or inflammatory conditions.",
        "possible_conditions": ["Arthritis", "Joint inflammation", "Muscle strain"],
        "care_advice": ["Rest affected joints.", "Use gentle stretching.", "Monitor swelling or worsening pain."],
        "red_flags": ["High fever", "Severe swelling", "Unable to walk", "Red hot joints"],
        "follow_up_questions": ["Which joints are affected?", "Any swelling?", "Is stiffness worse in the morning?"],
        "keywords_all": ["joint pain"],
        "keywords_any": [["stiffness", "swollen joints"]],
        "matched_keywords": ["joint pain", "stiffness"],
    },
    {
        "title": "Depression or anxiety pattern",
        "priority": 6,
        "risk_level": "Medium",
        "urgency": "Mental health support recommended",
        "summary": "Persistent sadness, anxiety, or sleep changes may suggest emotional or mental health concerns.",
        "possible_conditions": ["Anxiety", "Depression", "Stress-related condition"],
        "care_advice": ["Maintain sleep and routine.", "Reach out to supportive people.", "Consider professional counseling."],
        "red_flags": ["Thoughts of self-harm", "Severe hopelessness", "Panic attacks", "Inability to function"],
        "follow_up_questions": ["How long have symptoms lasted?", "Any sleep changes?", "Any thoughts of self-harm?"],
        "keywords_all": [],
        "keywords_any": [["anxiety", "panic"], ["sadness", "depressed"]],
        "matched_keywords": ["anxiety", "sadness"],
    },
    {
        "title": "Ear infection pattern",
        "priority": 5,
        "risk_level": "Low to Medium",
        "urgency": "Routine review if persistent",
        "summary": "Ear pain with fever or reduced hearing may suggest an ear infection.",
        "possible_conditions": ["Ear infection", "Middle ear inflammation"],
        "care_advice": ["Avoid inserting objects into the ear.", "Rest and hydrate.", "Seek review if pain continues."],
        "red_flags": ["Severe swelling", "Hearing loss", "High fever", "Fluid discharge"],
        "follow_up_questions": ["Any discharge from the ear?", "Any fever?", "Is hearing affected?"],
        "keywords_all": ["ear pain"],
        "keywords_any": [["hearing loss", "ear discharge"]],
        "matched_keywords": ["ear pain", "hearing loss"],
    },
    {
        "title": "Pneumonia pattern",
        "priority": 9,
        "risk_level": "High",
        "urgency": "Medical evaluation recommended",
        "summary": "Fever, cough, and breathing difficulty may suggest pneumonia or serious lung infection.",
        "possible_conditions": ["Pneumonia", "Lower respiratory infection"],
        "care_advice": ["Rest and hydrate.", "Monitor breathing closely.", "Seek prompt medical care."],
        "red_flags": ["Chest pain", "Low oxygen", "Confusion", "Rapid breathing"],
        "follow_up_questions": ["Is there mucus with cough?", "Any chest pain?", "Any breathing trouble?"],
        "keywords_all": ["fever", "cough"],
        "keywords_any": [["shortness of breath", "breathing difficulty"]],
        "matched_keywords": ["fever", "cough", "shortness of breath"],
    },

    {
        "title": "Food allergy emergency pattern",
        "priority": 10,
        "risk_level": "Critical",
        "urgency": "Emergency care immediately",
        "summary": "Swelling, rash, and breathing difficulty after food exposure may indicate severe allergy.",
        "possible_conditions": ["Anaphylaxis", "Severe food allergy"],
        "care_advice": ["Use emergency allergy medication if prescribed.", "Call emergency services.", "Avoid further exposure."],
        "red_flags": ["Facial swelling", "Breathing difficulty", "Fainting", "Rapid swelling"],
        "follow_up_questions": ["What food was eaten recently?", "Any throat tightness?", "Any known allergies?"],
        "keywords_all": [],
        "keywords_any": [["facial swelling", "swollen lips"], ["breathing difficulty", "shortness of breath"]],
        "matched_keywords": ["facial swelling", "breathing difficulty"],
    },

    {
        "title": "Kidney stone pattern",
        "priority": 8,
        "risk_level": "High",
        "urgency": "Same-day medical review",
        "summary": "Severe side or back pain with urinary symptoms may suggest kidney stones.",
        "possible_conditions": ["Kidney stone", "Urinary obstruction"],
        "care_advice": ["Drink water unless restricted.", "Seek medical evaluation.", "Monitor urine output."],
        "red_flags": ["Blood in urine", "Vomiting", "High fever", "Severe pain"],
        "follow_up_questions": ["Is pain one-sided?", "Any blood in urine?", "Any nausea or vomiting?"],
        "keywords_all": [],
        "keywords_any": [["flank pain", "side pain"], ["blood in urine"]],
        "matched_keywords": ["flank pain", "blood in urine"],
    },

    {
        "title": "Sinus infection pattern",
        "priority": 4,
        "risk_level": "Low",
        "urgency": "Routine care",
        "summary": "Facial pressure with congestion and headache may suggest sinus infection.",
        "possible_conditions": ["Sinusitis", "Upper respiratory infection"],
        "care_advice": ["Stay hydrated.", "Use steam inhalation carefully.", "Rest adequately."],
        "red_flags": ["Eye swelling", "Severe fever", "Vision changes", "Severe headache"],
        "follow_up_questions": ["Any facial pain?", "How long has congestion lasted?", "Any fever?"],
        "keywords_all": [],
        "keywords_any": [["sinus pressure", "facial pain"], ["nasal congestion", "blocked nose"]],
        "matched_keywords": ["sinus pressure", "nasal congestion"],
    },

    {
        "title": "Conjunctivitis pattern",
        "priority": 3,
        "risk_level": "Low",
        "urgency": "Routine care",
        "summary": "Red or itchy eyes with discharge may indicate conjunctivitis.",
        "possible_conditions": ["Pink eye", "Eye irritation", "Allergic conjunctivitis"],
        "care_advice": ["Avoid touching eyes.", "Wash hands frequently.", "Avoid sharing towels."],
        "red_flags": ["Vision loss", "Severe eye pain", "Light sensitivity", "Eye swelling"],
        "follow_up_questions": ["Is there discharge?", "One or both eyes affected?", "Any vision changes?"],
        "keywords_all": [],
        "keywords_any": [["red eyes", "eye redness"], ["eye discharge", "itchy eyes"]],
        "matched_keywords": ["red eyes", "itchy eyes"],
    },

    {
        "title": "Heat stroke pattern",
        "priority": 10,
        "risk_level": "Critical",
        "urgency": "Emergency treatment immediately",
        "summary": "High body temperature with confusion after heat exposure may indicate heat stroke.",
        "possible_conditions": ["Heat stroke", "Severe heat exhaustion"],
        "care_advice": ["Move to a cool area immediately.", "Cool the body with water or fans.", "Call emergency services."],
        "red_flags": ["Confusion", "Loss of consciousness", "Very high fever", "Seizures"],
        "follow_up_questions": ["Was there prolonged heat exposure?", "Any confusion or fainting?", "Any sweating present?"],
        "keywords_all": [],
        "keywords_any": [["heat exposure", "overheating"], ["confusion", "fainting"]],
        "matched_keywords": ["heat exposure", "confusion"],
    },

    {
        "title": "Seizure pattern",
        "priority": 10,
        "risk_level": "Critical",
        "urgency": "Emergency evaluation",
        "summary": "Sudden shaking, collapse, or loss of awareness may indicate a seizure.",
        "possible_conditions": ["Seizure disorder", "Epilepsy", "Fever-related seizure"],
        "care_advice": ["Keep the person safe from injury.", "Do not place objects in the mouth.", "Seek emergency care if prolonged."],
        "red_flags": ["Breathing problems", "Repeated seizures", "Confusion after seizure", "Injury during seizure"],
        "follow_up_questions": ["How long did it last?", "Any fever?", "Any previous seizure history?"],
        "keywords_all": [],
        "keywords_any": [["seizure", "convulsions"], ["loss of consciousness"]],
        "matched_keywords": ["seizure", "loss of consciousness"],
    },

    {
        "title": "Pregnancy complication warning pattern",
        "priority": 10,
        "risk_level": "Critical",
        "urgency": "Immediate obstetric evaluation",
        "summary": "Bleeding, severe abdominal pain, or severe headache during pregnancy needs urgent assessment.",
        "possible_conditions": ["Pregnancy complication", "Preeclampsia", "Miscarriage risk"],
        "care_advice": ["Seek emergency medical care.", "Avoid heavy activity.", "Monitor bleeding and pain."],
        "red_flags": ["Heavy bleeding", "Severe abdominal pain", "Severe headache", "Reduced fetal movement"],
        "follow_up_questions": ["How far along is the pregnancy?", "Is there bleeding?", "Any severe headache or swelling?"],
        "keywords_all": [],
        "keywords_any": [["pregnant", "pregnancy"], ["bleeding", "severe abdominal pain", "severe headache"]],
        "matched_keywords": ["pregnancy", "bleeding"],
    },
]
